version: '3.4'
services:
  worker:
    build: 
      context: .
      dockerfile: ./worker/Dockerfile
    #image: nTask_worker
    restart: unless-stopped
    container_name: nTask-worker
    ports:
      - 9981:8081
    depends_on:
      - manager
    env_file: .env
    command: --worker
    volumes:
      - ./worker.conf:/config/worker.conf
