version: '3.4'
services:
  manager:
    build: ./manager/
    #image: nettask_manager
    restart: unless-stopped
    container_name: nettask_manager
    ports:
      - 9980:8080
    depends_on:
      - db
    env_file: .env
    command: -swagger -manager 
    volumes:
      - ./manager.conf:/config/manager.conf
      - ./output/:/config/output/
  db:
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: manager
    #volumes:
