version: '3.4'
services:
  worker:
    build: ./worker/
    #image: nettask_worker
    restart: unless-stopped
    container_name: NetTask-worker
    ports:
      - 9981:8081
    depends_on:
      - manager
    env_file: .env
    command: --worker
    volumes:
      - ./worker.conf:/config/worker.conf
