CREATE TABLE IF NOT EXISTS worker (
    name VARCHAR(255) PRIMARY KEY,
    ip VARCHAR(255) NOT NULL,
    port VARCHAR(255) NOT NULL,
    working BOOLEAN,
    up BOOLEAN,
    UNIQUE (ip, port)
);

CREATE TABLE IF NOT EXISTS task (
    ID VARCHAR(255) PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status VARCHAR(255),
    workerName VARCHAR(255),
    output VARCHAR(255)
);
