basePath: /
definitions:
  globalstructs.Command:
    properties:
      args:
        type: string
      fileContent:
        type: string
      module:
        type: string
      output:
        type: string
      remoteFilePath:
        type: string
    type: object
  globalstructs.CommandSwagger:
    properties:
      args:
        type: string
      fileContent:
        type: string
      module:
        type: string
      remoteFilePath:
        type: string
    type: object
  globalstructs.Error:
    properties:
      error:
        type: string
    type: object
  globalstructs.Task:
    properties:
      callbackToken:
        type: string
      callbackURL:
        type: string
      command:
        items:
          $ref: '#/definitions/globalstructs.Command'
        type: array
      createdAt:
        type: string
      executedAt:
        type: string
      id:
        type: string
      name:
        type: string
      priority:
        type: integer
      status:
        description: pending, running, done, failed, deleted
        type: string
      updatedAt:
        type: string
      username:
        type: string
      workerName:
        type: string
    type: object
  globalstructs.TaskSwagger:
    properties:
      command:
        items:
          $ref: '#/definitions/globalstructs.CommandSwagger'
        type: array
      name:
        type: string
      priority:
        type: boolean
    type: object
  globalstructs.Worker:
    properties:
      IddleThreads:
        type: integer
      downCount:
        type: integer
      name:
        description: Workers name (unique)
        type: string
      up:
        type: boolean
    type: object
info:
  contact:
    email: me@r4ulcl.com
    name: r4ulcl
    url: https://r4ulcl.com
  description: nTask API documentation
  license:
    name: GPL-3.0
    url: https://github.com/r4ulcl/nTask/blob/main/LICENSE
  title: nTask API
  version: "1.0"
paths:
  /status:
    get:
      consumes:
      - application/json
      description: Get status summary from Manager
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globalstructs.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/globalstructs.Error'
      security:
      - ApiKeyAuth: []
      summary: Get status summary from Manager
      tags:
      - status
  /task:
    get:
      consumes:
      - application/json
      description: Get status of tasks
      parameters:
      - description: Task ID
        in: query
        name: ID
        type: string
      - description: Task command
        in: query
        name: command
        type: string
      - description: Task name
        in: query
        name: name
        type: string
      - description: Task createdAt
        in: query
        name: createdAt
        type: string
      - description: Task updatedAt
        in: query
        name: updatedAt
        type: string
      - description: Task executedAt
        in: query
        name: executedAt
        type: string
      - description: Task status
        enum:
        - pending
        - running
        - done
        - failed
        - deleted
        in: query
        name: status
        type: string
      - description: Task workerName
        in: query
        name: workerName
        type: string
      - description: Task username
        in: query
        name: username
        type: string
      - description: Task priority
        in: query
        name: priority
        type: string
      - description: Task callbackURL
        in: query
        name: callbackURL
        type: string
      - description: Task callbackToken
        in: query
        name: callbackToken
        type: string
      - description: limit output DB
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/globalstructs.Task'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globalstructs.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/globalstructs.Error'
      security:
      - ApiKeyAuth: []
      summary: Get all tasks
      tags:
      - task
    post:
      consumes:
      - application/json
      description: Add a new tasks
      parameters:
      - description: Task object to create
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/globalstructs.TaskSwagger'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/globalstructs.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globalstructs.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/globalstructs.Error'
      security:
      - ApiKeyAuth: []
      summary: Add a new tasks
      tags:
      - task
  /task/{ID}:
    delete:
      consumes:
      - application/json
      description: Delete a tasks
      parameters:
      - description: task ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/globalstructs.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globalstructs.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/globalstructs.Error'
      security:
      - ApiKeyAuth: []
      summary: Delete a tasks
      tags:
      - task
    get:
      consumes:
      - application/json
      description: Get status of a task
      parameters:
      - description: task ID
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/globalstructs.Task'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globalstructs.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/globalstructs.Error'
      security:
      - ApiKeyAuth: []
      summary: Get status of a task
      tags:
      - task
  /worker:
    get:
      consumes:
      - application/json
      description: Handle worker request
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/globalstructs.Worker'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globalstructs.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/globalstructs.Error'
      security:
      - ApiKeyAuth: []
      summary: Get workers
      tags:
      - worker
    post:
      consumes:
      - application/json
      description: Add a worker, normally done by the worker
      parameters:
      - description: Worker object to create
        in: body
        name: worker
        required: true
        schema:
          $ref: '#/definitions/globalstructs.Worker'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/globalstructs.Worker'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globalstructs.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/globalstructs.Error'
      security:
      - ApiKeyAuth: []
      summary: Add a worker
      tags:
      - worker
  /worker/{NAME}:
    delete:
      consumes:
      - application/json
      description: Remove a worker from the system
      parameters:
      - description: Worker NAME
        in: path
        name: NAME
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globalstructs.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/globalstructs.Error'
      security:
      - ApiKeyAuth: []
      summary: Remove a worker
      tags:
      - worker
    get:
      consumes:
      - application/json
      description: Get status of worker
      parameters:
      - description: Worker NAME
        in: path
        name: NAME
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/globalstructs.Worker'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/globalstructs.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/globalstructs.Error'
      security:
      - ApiKeyAuth: []
      summary: Get status of worker
      tags:
      - worker
schemes:
- https
- http
security:
- ApiKeyAuth: []
securityDefinitions:
  ApiKeyAuth:
    description: ApiKeyAuth to login
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
